export GRANT_TYPE='client_credentials'
export YELP_CONSUMER_KEY='SRLtYeYdejihqv8XZWM8IA'
export YELP_CONSUMER_SECRET='TvDg3sFbtkRmhTqgsjdwrWGAdT7BuGSzftBUF8UACjO98J3gCxRHKcfOLQMOkXZ1'
export MONGODB_URI='mongodb://lisa:lisa@ds017672.mlab.com:17672/compleat'
export SECRET='my dream job is to be a dream consultant - daniel'
